language: go
go:
- 1.12
env:
- GIMME_OS=linux GIMME_ARCH=amd64 CGO_ENABLED=0
gobuild_args: -tags netgo
script:
- go test -tags netgo -v ./...
before_deploy:
- go build -ldflags "-X main.version=$TRAVIS_BRANCH -X main.commitHash=$TRAVIS_COMMIT" -a -tags netgo -v ./...
- tar --owner=root --group=root -zcvf varnish-cli-bridge-$TRAVIS_BRANCH-$GIMME_OS-$GIMME_ARCH.tar.gz varnish-cli-bridge
deploy:
  provider: releases
  api_key:
    secure: JHfOuKxjwXGeH9t+gUjPtC2DtO+QTnNkUq9nM0gNLWB3p4X+D6XJoCurbMnl20s3fjtNNqPgmLH5Hm81nhrhu7nRvU53jVmtWo11yhfTcngEoxW/5zUA3iiL+HX7dfUIjsaMb5KTZdMziTdSCpjjqDJRqSTP20sWm85lXZAWVK+wRCZNVj7m0tRVOWyNmrKLF/4XizL0sULLqt1Q3TP6KKLjTaInhuk06yS3I3qMp27Vv/+PhNBIJNSJfQ66FLZQrtgSeeieHl4Ok3OEKYRQEfCkE4RCYPYY5yVKxNGzCHW+6SuP70e/6XvZvKKJPaXLUR6aecg5GNUbmjetDCW2d3xWW3N7a/RXyCtMgdtelrrYMcVtol6KWr7z6tePCVn1RE60SCk1iJ51FtslYLWaVhPGCD30fTqmMizJeHs0wuoJ6OLvwKXVmGavkvxcE54jp+y2v10rSGPyak22oy1StU7XopmCTr++3W2u4GqqhvCB1L7ycP6OsPHk3Zdx9WF8n1V3VBaMHIG72XBGzXFIh4NkyhbI9yR986HzvoIL4sZM6wH9FZVLDuL1OXkdyLaYEmUFI8jB1oYknzdUcJd+a6xQSQzifnuIT8ni7h3BpaYakBqMHsGZ1dOfFnnJZiFKOOurgopzxsLun2wTbQeb9zbEzCZMDnSXuriJivXcmfA=
  file: varnish-cli-bridge-$TRAVIS_BRANCH-$GIMME_OS-$GIMME_ARCH.tar.gz
  skip_cleanup: true
  on:
    tags: true
